### ISSUE TITLE
Business Logic Layer Implementation

### ISSUE THREAD

**Issue by mukund-9652** [mukund-9652/Agile-Project-Management-Portal#3]
Implement the Business Logic Layer By working on the following: 
1. Service (Interface implementation of the given Services)
2. Service Implementation (Implementing the interfaces as services)
3. Model Mapper (Implementing necessary model mapping to map the entities to their respective DTO's)

Also adhere to the following:

1.	Create the service classes following the single responsibility principle which perform the given operations as follows :

      a.	Return clients list
      b.	Add new project
      c.	Update existing project
      d.	Return projects list
      e.	Add new resource

2.	Following business rules must be implemented as part of the business service class

      a.	UserId must be auto-generated. It should be in the format XY0000. First 2 letters of lastname followed by a 4 digit number
      b.	Phone number should be exactly 10 digits long
      c.	Email address should always have @cognizant.com
      d.	Firstname and lastname should only have alphabets and last name must be minimum 3 characters long.
      e.	Each project is allowed a maximum of 50 developers and 10 testers, if the limit exceeds then raise a user-defined exception as “MaximumResourceLimitReachedException”.
      f.	Adding a resource to a cancelled projects should not be allowed.

**Comment by Abhishekm0410** [comment]
I would like to work on this . Is there any way I can help?

**Comment by mukund-9652** [comment]
@Abhishekm0410 Hi abhishek, I am actually trying to personally work on this project and trying learn more on github controls. Will work on another project together if possible. Connect with me on LinkedIn: [https://www.linkedin.com/in/mukundrs/](https://www.linkedin.com/in/mukundrs/)

**Comment by Abhishekm0410** [comment]
Sure ,Thanks for reaching out.

**Comment by mukund-9652** [comment]
@Abhishekm0410 thanks for taking interest in this. I will surely reach you out in the next project that I make.
